package net.hasor.db.jdbc.types;
public class xxxTypeTest {
    //AbstractTypeHandler
    //ArrayTypeHandler
    //NumberTypeHandler
    //ObjectTypeHandler
    //SqlXmlForInputStreamTypeHandler
    //SqlXmlForReaderTypeHandler
    //SqlXmlTypeHandler
    //URLTypeHandler
    //
    //BlobBytesForWrapTypeHandler
    //BlobBytesTypeHandler
    //BlobInputStreamTypeHandler
    //BytesForWrapTypeHandler
    //BytesInputStreamTypeHandler
    //BytesTypeHandler
    //
    //SqlDateTypeHandler
    //SqlTimestampTypeHandler
    //SqlTimeTypeHandler
    //DateTypeHandler
    //DateOnlyTypeHandler
    //TimeOnlyTypeHandler
    //
    //LocalDateTimeTypeHandler
    //LocalDateTypeHandler
    //LocalTimeTypeHandler
    //
    //YearMonthOfNumberTypeHandler
    //YearMonthOfStringTypeHandler
    //YearMonthOfTimeTypeHandler
    //
    //YearOfNumberTypeHandler
    //YearOfStringTypeHandler
    //YearOfTimeTypeHandler
    //
    //InstantTypeHandler
    //JapaneseDateTypeHandler
    //ZonedDateTimeTypeHandler
    //OffsetDateTimeForSqlTypeHandler
    //OffsetDateTimeForUTCTypeHandler
    //OffsetTimeForSqlTypeHandler
    //OffsetTimeForUTCTypeHandler
}