/* Generated By:JavaCC: Do not edit this line. TokenMgrError.java Version 6.0 */
/* JavaCCOptions: */
package net.hasor.graphql.dsl.parser;
/** Token Manager Error. */
enum GraphQLToType {
    ToParam, ToField
}