/* Generated By:JavaCC: Do not edit this line. TokenMgrError.java Version 6.0 */
/* JavaCCOptions: */
package net.hasor.data.ql.dsl.parser;
/** Token Manager Error. */
enum DataQLToType {
    ToParam, ToField
}