/* GraphParser.java */
/* Generated By:JavaCC: Do not edit this line. GraphParser.java */
package net.hasor.data.ql.dsl.parser;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
public class GraphParser implements GraphParserConstants {
    private GraphParser() {
    }
    //
    public static void parserGraphQL(String queryString) throws ParseException {
        GraphParser parser = new GraphParser(new ByteArrayInputStream(queryString.getBytes()));
        parser.rootBlock();
    }
    public static void parserGraphQL(InputStream inputStream, String encoding) throws ParseException {
        GraphParser parser = new GraphParser(inputStream, encoding);
        parser.rootBlock();
    }
    //-----------------------------------------------------------------------------
    // .标识符
    final public void identifier() throws ParseException {
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
        case IDENTIFIER: {
            jj_consume_token(IDENTIFIER);
            break;
        }
        case OCBRR: {
            jj_consume_token(OCBRR);
            jj_consume_token(IDENTIFIER);
            jj_consume_token(CCBR);
            break;
        }
        default:
            jj_la1[0] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
        }
    }
    // .带引号的字符串
    final public void stringValue() throws ParseException {
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
        case STR_DOUBLE_QUOTED: {
            jj_consume_token(STR_DOUBLE_QUOTED);
            break;
        }
        case STR_SINGLE_QUOTED: {
            jj_consume_token(STR_SINGLE_QUOTED);
            break;
        }
        case STR_EMPTY: {
            jj_consume_token(STR_EMPTY);
            break;
        }
        default:
            jj_la1[1] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
        }
    }
    // .空值
    final public void nullValue() throws ParseException {
        jj_consume_token(NULL);
    }
    // .布尔
    final public void booleanValue() throws ParseException {
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
        case TRUE: {
            jj_consume_token(TRUE);
            break;
        }
        case FALSE: {
            jj_consume_token(FALSE);
            break;
        }
        default:
            jj_la1[2] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
        }
    }
    // .数字
    final public void numberValue() throws ParseException {
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
        case DECIMAL_NUM: {
            jj_consume_token(DECIMAL_NUM);
            break;
        }
        case INTEGER_NUM: {
            jj_consume_token(INTEGER_NUM);
            break;
        }
        case HEX_NUM: {
            jj_consume_token(HEX_NUM);
            break;
        }
        case OCTAL_NUM: {
            jj_consume_token(OCTAL_NUM);
            break;
        }
        case BINARY_NUM: {
            jj_consume_token(BINARY_NUM);
            break;
        }
        default:
            jj_la1[3] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
        }
    }
    // .列表：[ ... ]
    final public void list() throws ParseException {
        if (jj_2_1(2)) {
            jj_consume_token(OBRA);
            jj_consume_token(CBRA);
        } else {
            switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
            case OBRA: {
                jj_consume_token(OBRA);
                expression();
                label_1:
                while (true) {
                    switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
                    case COMMA: {
                        ;
                        break;
                    }
                    default:
                        jj_la1[4] = jj_gen;
                        break label_1;
                    }
                    jj_consume_token(COMMA);
                    expression();
                }
                jj_consume_token(CBRA);
                break;
            }
            default:
                jj_la1[5] = jj_gen;
                jj_consume_token(-1);
                throw new ParseException();
            }
        }
    }
    // .对象：
    final public void object() throws ParseException {
        if (jj_2_2(2)) {
            jj_consume_token(OCBR);
            jj_consume_token(CCBR);
        } else {
            switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
            case OCBR: {
                jj_consume_token(OCBR);
                stringValue();
                switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
                case COLON: {
                    jj_consume_token(COLON);
                    expression();
                    break;
                }
                default:
                    jj_la1[6] = jj_gen;
                    ;
                }
                label_2:
                while (true) {
                    switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
                    case COMMA: {
                        ;
                        break;
                    }
                    default:
                        jj_la1[7] = jj_gen;
                        break label_2;
                    }
                    jj_consume_token(COMMA);
                    stringValue();
                    switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
                    case COLON: {
                        jj_consume_token(COLON);
                        expression();
                        break;
                    }
                    default:
                        jj_la1[8] = jj_gen;
                        ;
                    }
                }
                jj_consume_token(CCBR);
                break;
            }
            default:
                jj_la1[9] = jj_gen;
                jj_consume_token(-1);
                throw new ParseException();
            }
        }
    }
    //-----------------------------------------------------------------------------
    // .表达式 =   表达式 or 表达式 + 运算符
    final public void expression() throws ParseException {
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
        case OPAR: {
            jj_consume_token(OPAR);
            expression();
            jj_consume_token(CPAR);
            switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
            case QUEM:
            case PLUS:
            case MINUS:
            case STAR:
            case SLASH:
            case REM:
            case ALI:
            case GT:
            case GE:
            case LT:
            case LE:
            case EQ:
            case NE:
            case BIT_AND:
            case BIT_OR:
            case XOR:
            case LSHIFT:
            case RSIGNEDSHIFT:
            case RUNSIGNEDSHIFT:
            case SC_OR:
            case SC_AND: {
                extExpression();
                break;
            }
            default:
                jj_la1[10] = jj_gen;
                ;
            }
            break;
        }
        default:
            jj_la1[12] = jj_gen;
            if (jj_2_3(2147483647)) {
                oneExpression();
            } else {
                switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
                case INTEGER_NUM:
                case HEX_NUM:
                case OCTAL_NUM:
                case BINARY_NUM:
                case DECIMAL_NUM:
                case TRUE:
                case FALSE:
                case NULL:
                case OBRA:
                case OCBRR:
                case OCBR:
                case STR_DOUBLE_QUOTED:
                case STR_SINGLE_QUOTED:
                case STR_EMPTY:
                case IDENTIFIER: {
                    basicValue();
                    switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
                    case QUEM:
                    case PLUS:
                    case MINUS:
                    case STAR:
                    case SLASH:
                    case REM:
                    case ALI:
                    case GT:
                    case GE:
                    case LT:
                    case LE:
                    case EQ:
                    case NE:
                    case BIT_AND:
                    case BIT_OR:
                    case XOR:
                    case LSHIFT:
                    case RSIGNEDSHIFT:
                    case RUNSIGNEDSHIFT:
                    case SC_OR:
                    case SC_AND: {
                        extExpression();
                        break;
                    }
                    default:
                        jj_la1[11] = jj_gen;
                        ;
                    }
                    break;
                }
                default:
                    jj_la1[13] = jj_gen;
                    jj_consume_token(-1);
                    throw new ParseException();
                }
            }
        }
    }
    final public void oneExpression() throws ParseException {
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
        case BANG:
        case INCR:
        case DECR: {
            switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
            case BANG: {
                jj_consume_token(BANG);
                break;
            }
            case INCR: {
                jj_consume_token(INCR);
                break;
            }
            case DECR: {
                jj_consume_token(DECR);
                break;
            }
            default:
                jj_la1[14] = jj_gen;
                jj_consume_token(-1);
                throw new ParseException();
            }
            basicValue();
            break;
        }
        case INTEGER_NUM:
        case HEX_NUM:
        case OCTAL_NUM:
        case BINARY_NUM:
        case DECIMAL_NUM:
        case TRUE:
        case FALSE:
        case NULL:
        case OBRA:
        case OCBRR:
        case OCBR:
        case STR_DOUBLE_QUOTED:
        case STR_SINGLE_QUOTED:
        case STR_EMPTY:
        case IDENTIFIER: {
            basicValue();
            switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
            case INCR: {
                jj_consume_token(INCR);
                break;
            }
            case DECR: {
                jj_consume_token(DECR);
                break;
            }
            default:
                jj_la1[15] = jj_gen;
                jj_consume_token(-1);
                throw new ParseException();
            }
            break;
        }
        default:
            jj_la1[16] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
        }
    }
    final public void extExpression() throws ParseException {
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
        case PLUS:
        case MINUS:
        case STAR:
        case SLASH:
        case REM:
        case ALI:
        case GT:
        case GE:
        case LT:
        case LE:
        case EQ:
        case NE:
        case BIT_AND:
        case BIT_OR:
        case XOR:
        case LSHIFT:
        case RSIGNEDSHIFT:
        case RUNSIGNEDSHIFT:
        case SC_OR:
        case SC_AND: {
            twoExpression();
            break;
        }
        case QUEM: {
            threeExpression();
            break;
        }
        default:
            jj_la1[17] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
        }
    }
    final public void twoExpression() throws ParseException {
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
        case PLUS: {
            jj_consume_token(PLUS);
            break;
        }
        case MINUS: {
            jj_consume_token(MINUS);
            break;
        }
        case STAR: {
            jj_consume_token(STAR);
            break;
        }
        case SLASH: {
            jj_consume_token(SLASH);
            break;
        }
        case REM: {
            jj_consume_token(REM);
            break;
        }
        case ALI: {
            jj_consume_token(ALI);
            break;
        }
        case GT: {
            jj_consume_token(GT);
            break;
        }
        case GE: {
            jj_consume_token(GE);
            break;
        }
        case LT: {
            jj_consume_token(LT);
            break;
        }
        case LE: {
            jj_consume_token(LE);
            break;
        }
        case EQ: {
            jj_consume_token(EQ);
            break;
        }
        case NE: {
            jj_consume_token(NE);
            break;
        }
        case BIT_AND: {
            jj_consume_token(BIT_AND);
            break;
        }
        case BIT_OR: {
            jj_consume_token(BIT_OR);
            break;
        }
        case XOR: {
            jj_consume_token(XOR);
            break;
        }
        case LSHIFT: {
            jj_consume_token(LSHIFT);
            break;
        }
        case RSIGNEDSHIFT: {
            jj_consume_token(RSIGNEDSHIFT);
            break;
        }
        case RUNSIGNEDSHIFT: {
            jj_consume_token(RUNSIGNEDSHIFT);
            break;
        }
        case SC_OR: {
            jj_consume_token(SC_OR);
            break;
        }
        case SC_AND: {
            jj_consume_token(SC_AND);
            break;
        }
        default:
            jj_la1[18] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
        }
        expression();
    }
    final public void threeExpression() throws ParseException {
        jj_consume_token(QUEM);
        expression();
        jj_consume_token(COLON);
        expression();
    }
    // .值
    final public void basicValue() throws ParseException {
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
        case INTEGER_NUM:
        case HEX_NUM:
        case OCTAL_NUM:
        case BINARY_NUM:
        case DECIMAL_NUM:
        case TRUE:
        case FALSE:
        case NULL:
        case STR_DOUBLE_QUOTED:
        case STR_SINGLE_QUOTED:
        case STR_EMPTY: {
            primitiveValue();
            break;
        }
        case OCBRR:
        case IDENTIFIER: {
            identifier();
            switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
            case OPAR: {
                funCall();
                break;
            }
            default:
                jj_la1[19] = jj_gen;
                ;
            }
            break;
        }
        case OBRA: {
            list();
            break;
        }
        case OCBR: {
            object();
            break;
        }
        default:
            jj_la1[20] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
        }
    }
    final public void primitiveValue() throws ParseException {
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
        case STR_DOUBLE_QUOTED:
        case STR_SINGLE_QUOTED:
        case STR_EMPTY: {
            stringValue();
            break;
        }
        case NULL: {
            nullValue();
            break;
        }
        case TRUE:
        case FALSE: {
            booleanValue();
            break;
        }
        case INTEGER_NUM:
        case HEX_NUM:
        case OCTAL_NUM:
        case BINARY_NUM:
        case DECIMAL_NUM: {
            numberValue();
            break;
        }
        default:
            jj_la1[21] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
        }
    }
    //-----------------------------------------------------------------------------
    // .参数集：(xx , xx , xx)
    final public void paramSet() throws ParseException {
        if (jj_2_4(2)) {
            jj_consume_token(OPAR);
            jj_consume_token(CPAR);
        } else {
            switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
            case OPAR: {
                jj_consume_token(OPAR);
                paramItem();
                label_3:
                while (true) {
                    switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
                    case COMMA: {
                        ;
                        break;
                    }
                    default:
                        jj_la1[22] = jj_gen;
                        break label_3;
                    }
                    jj_consume_token(COMMA);
                    paramItem();
                }
                jj_consume_token(CPAR);
                break;
            }
            default:
                jj_la1[23] = jj_gen;
                jj_consume_token(-1);
                throw new ParseException();
            }
        }
    }
    // .函数参数
    final public void paramItem() throws ParseException {
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
        case LAMBDA: {
            lambdaCall();
            break;
        }
        case INTEGER_NUM:
        case HEX_NUM:
        case OCTAL_NUM:
        case BINARY_NUM:
        case DECIMAL_NUM:
        case TRUE:
        case FALSE:
        case NULL:
        case OPAR:
        case OBRA:
        case OCBRR:
        case OCBR:
        case BANG:
        case INCR:
        case DECR:
        case STR_DOUBLE_QUOTED:
        case STR_SINGLE_QUOTED:
        case STR_EMPTY:
        case IDENTIFIER: {
            expression();
            break;
        }
        default:
            jj_la1[24] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
        }
    }
    // .函数调用
    final public void funCall() throws ParseException {
        paramSet();
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
        case OBRA: {
            list();
            break;
        }
        case OCBR: {
            object();
            break;
        }
        case 76: {
            jj_consume_token(76);
            break;
        }
        default:
            jj_la1[25] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
        }
    }
    // .Lambda函数： lambda : (obj,obj2) -> {}
    final public void lambdaCall() throws ParseException {
        jj_consume_token(LAMBDA);
        jj_consume_token(COLON);
        if (jj_2_5(2)) {
            jj_consume_token(OPAR);
            jj_consume_token(CPAR);
        } else {
            switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
            case OPAR: {
                jj_consume_token(OPAR);
                jj_consume_token(IDENTIFIER);
                label_4:
                while (true) {
                    switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
                    case COMMA: {
                        ;
                        break;
                    }
                    default:
                        jj_la1[26] = jj_gen;
                        break label_4;
                    }
                    jj_consume_token(COMMA);
                    jj_consume_token(IDENTIFIER);
                }
                jj_consume_token(CPAR);
                break;
            }
            default:
                jj_la1[27] = jj_gen;
                jj_consume_token(-1);
                throw new ParseException();
            }
        }
        jj_consume_token(77);
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
        case OCBR: {
            jj_consume_token(OCBR);
            blockSet();
            jj_consume_token(CCBR);
            break;
        }
        default:
            jj_la1[28] = jj_gen;
            if (jj_2_6(2147483647)) {
                block();
            } else {
                jj_consume_token(-1);
                throw new ParseException();
            }
        }
    }
    //-----------------------------------------------------------------------------
    // .函数
    final public void varBlock() throws ParseException {
        jj_consume_token(VAR);
        identifier();
        jj_consume_token(ASS);
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
        case LAMBDA: {
            lambdaCall();
            break;
        }
        case INTEGER_NUM:
        case HEX_NUM:
        case OCTAL_NUM:
        case BINARY_NUM:
        case DECIMAL_NUM:
        case TRUE:
        case FALSE:
        case NULL:
        case OPAR:
        case OBRA:
        case OCBRR:
        case OCBR:
        case BANG:
        case INCR:
        case DECR:
        case STR_DOUBLE_QUOTED:
        case STR_SINGLE_QUOTED:
        case STR_EMPTY:
        case IDENTIFIER: {
            expression();
            break;
        }
        default:
            jj_la1[29] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
        }
    }
    // .反回
    final public void returnBlock() throws ParseException {
        jj_consume_token(RETURN);
        expression();
    }
    // .选项指令
    final public void optionBlock() throws ParseException {
        jj_consume_token(OPTION);
        identifier();
        jj_consume_token(ASS);
        primitiveValue();
    }
    // .判断
    final public void ifBlock() throws ParseException {
        jj_consume_token(IF);
        jj_consume_token(OPAR);
        expression();
        jj_consume_token(CPAR);
        blockSet();
        label_5:
        while (true) {
            switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
            case ELSEIF: {
                ;
                break;
            }
            default:
                jj_la1[30] = jj_gen;
                break label_5;
            }
            jj_consume_token(ELSEIF);
            jj_consume_token(OPAR);
            expression();
            jj_consume_token(CPAR);
            blockSet();
        }
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
        case ELSE: {
            jj_consume_token(ELSE);
            blockSet();
            break;
        }
        default:
            jj_la1[31] = jj_gen;
            ;
        }
        jj_consume_token(END);
    }
    // .异常
    final public void throwBlock() throws ParseException {
        jj_consume_token(THROW);
        if (jj_2_7(2147483647)) {
            throwBlockStatus();
            expression();
        } else {
            switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
            case INTEGER_NUM:
            case HEX_NUM:
            case OCTAL_NUM:
            case BINARY_NUM:
            case DECIMAL_NUM:
            case TRUE:
            case FALSE:
            case NULL:
            case OPAR:
            case OBRA:
            case OCBRR:
            case OCBR:
            case BANG:
            case INCR:
            case DECR:
            case STR_DOUBLE_QUOTED:
            case STR_SINGLE_QUOTED:
            case STR_EMPTY:
            case IDENTIFIER: {
                expression();
                break;
            }
            default:
                jj_la1[32] = jj_gen;
                jj_consume_token(-1);
                throw new ParseException();
            }
        }
    }
    final public void throwBlockStatus() throws ParseException {
        numberValue();
        jj_consume_token(COMMA);
    }
    // .块
    final public void block() throws ParseException {
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
        case VAR: {
            varBlock();
            break;
        }
        case IF: {
            ifBlock();
            break;
        }
        case RETURN: {
            returnBlock();
            break;
        }
        case THROW: {
            throwBlock();
            break;
        }
        default:
            jj_la1[33] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
        }
    }
    // .块
    final public void blockSet() throws ParseException {
        label_6:
        while (true) {
            switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
            case IF:
            case RETURN:
            case THROW:
            case VAR: {
                ;
                break;
            }
            default:
                jj_la1[34] = jj_gen;
                break label_6;
            }
            block();
            switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
            case SEMI: {
                jj_consume_token(SEMI);
                break;
            }
            default:
                jj_la1[35] = jj_gen;
                ;
            }
        }
    }
    // 入口
    final public void rootBlock() throws ParseException {
        label_7:
        while (true) {
            switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
            case OPTION: {
                ;
                break;
            }
            default:
                jj_la1[36] = jj_gen;
                break label_7;
            }
            optionBlock();
            switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
            case SEMI: {
                jj_consume_token(SEMI);
                break;
            }
            default:
                jj_la1[37] = jj_gen;
                ;
            }
        }
        blockSet();
        jj_consume_token(0);
    }
    private boolean jj_2_1(int xla) {
        jj_la = xla;
        jj_lastpos = jj_scanpos = token;
        try {
            return !jj_3_1();
        } catch (LookaheadSuccess ls) {
            return true;
        } finally {
            jj_save(0, xla);
        }
    }
    private boolean jj_2_2(int xla) {
        jj_la = xla;
        jj_lastpos = jj_scanpos = token;
        try {
            return !jj_3_2();
        } catch (LookaheadSuccess ls) {
            return true;
        } finally {
            jj_save(1, xla);
        }
    }
    private boolean jj_2_3(int xla) {
        jj_la = xla;
        jj_lastpos = jj_scanpos = token;
        try {
            return !jj_3_3();
        } catch (LookaheadSuccess ls) {
            return true;
        } finally {
            jj_save(2, xla);
        }
    }
    private boolean jj_2_4(int xla) {
        jj_la = xla;
        jj_lastpos = jj_scanpos = token;
        try {
            return !jj_3_4();
        } catch (LookaheadSuccess ls) {
            return true;
        } finally {
            jj_save(3, xla);
        }
    }
    private boolean jj_2_5(int xla) {
        jj_la = xla;
        jj_lastpos = jj_scanpos = token;
        try {
            return !jj_3_5();
        } catch (LookaheadSuccess ls) {
            return true;
        } finally {
            jj_save(4, xla);
        }
    }
    private boolean jj_2_6(int xla) {
        jj_la = xla;
        jj_lastpos = jj_scanpos = token;
        try {
            return !jj_3_6();
        } catch (LookaheadSuccess ls) {
            return true;
        } finally {
            jj_save(5, xla);
        }
    }
    private boolean jj_2_7(int xla) {
        jj_la = xla;
        jj_lastpos = jj_scanpos = token;
        try {
            return !jj_3_7();
        } catch (LookaheadSuccess ls) {
            return true;
        } finally {
            jj_save(6, xla);
        }
    }
    private boolean jj_3R_52() {
        if (jj_scan_token(OPAR))
            return true;
        if (jj_scan_token(IDENTIFIER))
            return true;
        Token xsp;
        while (true) {
            xsp = jj_scanpos;
            if (jj_3R_65()) {
                jj_scanpos = xsp;
                break;
            }
        }
        if (jj_scan_token(CPAR))
            return true;
        return false;
    }
    private boolean jj_3_5() {
        if (jj_scan_token(OPAR))
            return true;
        if (jj_scan_token(CPAR))
            return true;
        return false;
    }
    private boolean jj_3R_41() {
        if (jj_scan_token(LAMBDA))
            return true;
        if (jj_scan_token(COLON))
            return true;
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3_5()) {
            jj_scanpos = xsp;
            if (jj_3R_52())
                return true;
        }
        if (jj_scan_token(77))
            return true;
        xsp = jj_scanpos;
        if (jj_3R_53()) {
            jj_scanpos = xsp;
            if (jj_3R_54())
                return true;
        }
        return false;
    }
    private boolean jj_3R_61() {
        if (jj_3R_39())
            return true;
        return false;
    }
    private boolean jj_3R_60() {
        if (jj_3R_38())
            return true;
        return false;
    }
    private boolean jj_3R_49() {
        if (jj_3R_59())
            return true;
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3R_60()) {
            jj_scanpos = xsp;
            if (jj_3R_61()) {
                jj_scanpos = xsp;
                if (jj_scan_token(76))
                    return true;
            }
        }
        return false;
    }
    private boolean jj_3R_76() {
        if (jj_3R_30())
            return true;
        return false;
    }
    private boolean jj_3R_72() {
        if (jj_scan_token(COMMA))
            return true;
        if (jj_3R_71())
            return true;
        return false;
    }
    private boolean jj_3R_75() {
        if (jj_3R_41())
            return true;
        return false;
    }
    private boolean jj_3R_71() {
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3R_75()) {
            jj_scanpos = xsp;
            if (jj_3R_76())
                return true;
        }
        return false;
    }
    private boolean jj_3R_67() {
        if (jj_scan_token(OPAR))
            return true;
        if (jj_3R_71())
            return true;
        Token xsp;
        while (true) {
            xsp = jj_scanpos;
            if (jj_3R_72()) {
                jj_scanpos = xsp;
                break;
            }
        }
        if (jj_scan_token(CPAR))
            return true;
        return false;
    }
    private boolean jj_3_4() {
        if (jj_scan_token(OPAR))
            return true;
        if (jj_scan_token(CPAR))
            return true;
        return false;
    }
    private boolean jj_3R_59() {
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3_4()) {
            jj_scanpos = xsp;
            if (jj_3R_67())
                return true;
        }
        return false;
    }
    private boolean jj_3R_48() {
        if (jj_3R_17())
            return true;
        return false;
    }
    private boolean jj_3R_47() {
        if (jj_3R_58())
            return true;
        return false;
    }
    private boolean jj_3R_46() {
        if (jj_3R_57())
            return true;
        return false;
    }
    private boolean jj_3R_37() {
        if (jj_3R_49())
            return true;
        return false;
    }
    private boolean jj_3R_36() {
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3R_46()) {
            jj_scanpos = xsp;
            if (jj_scan_token(27)) {
                jj_scanpos = xsp;
                if (jj_3R_47()) {
                    jj_scanpos = xsp;
                    if (jj_3R_48())
                        return true;
                }
            }
        }
        return false;
    }
    private boolean jj_3R_26() {
        if (jj_3R_39())
            return true;
        return false;
    }
    private boolean jj_3R_25() {
        if (jj_3R_38())
            return true;
        return false;
    }
    private boolean jj_3R_24() {
        if (jj_3R_27())
            return true;
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3R_37())
            jj_scanpos = xsp;
        return false;
    }
    private boolean jj_3R_23() {
        if (jj_3R_36())
            return true;
        return false;
    }
    private boolean jj_3R_18() {
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3R_23()) {
            jj_scanpos = xsp;
            if (jj_3R_24()) {
                jj_scanpos = xsp;
                if (jj_3R_25()) {
                    jj_scanpos = xsp;
                    if (jj_3R_26())
                        return true;
                }
            }
        }
        return false;
    }
    private boolean jj_3R_74() {
        if (jj_scan_token(QUEM))
            return true;
        if (jj_3R_30())
            return true;
        if (jj_scan_token(COLON))
            return true;
        if (jj_3R_30())
            return true;
        return false;
    }
    private boolean jj_3R_73() {
        Token xsp;
        xsp = jj_scanpos;
        if (jj_scan_token(46)) {
            jj_scanpos = xsp;
            if (jj_scan_token(47)) {
                jj_scanpos = xsp;
                if (jj_scan_token(48)) {
                    jj_scanpos = xsp;
                    if (jj_scan_token(49)) {
                        jj_scanpos = xsp;
                        if (jj_scan_token(50)) {
                            jj_scanpos = xsp;
                            if (jj_scan_token(51)) {
                                jj_scanpos = xsp;
                                if (jj_scan_token(52)) {
                                    jj_scanpos = xsp;
                                    if (jj_scan_token(53)) {
                                        jj_scanpos = xsp;
                                        if (jj_scan_token(54)) {
                                            jj_scanpos = xsp;
                                            if (jj_scan_token(55)) {
                                                jj_scanpos = xsp;
                                                if (jj_scan_token(56)) {
                                                    jj_scanpos = xsp;
                                                    if (jj_scan_token(57)) {
                                                        jj_scanpos = xsp;
                                                        if (jj_scan_token(58)) {
                                                            jj_scanpos = xsp;
                                                            if (jj_scan_token(59)) {
                                                                jj_scanpos = xsp;
                                                                if (jj_scan_token(60)) {
                                                                    jj_scanpos = xsp;
                                                                    if (jj_scan_token(61)) {
                                                                        jj_scanpos = xsp;
                                                                        if (jj_scan_token(62)) {
                                                                            jj_scanpos = xsp;
                                                                            if (jj_scan_token(63)) {
                                                                                jj_scanpos = xsp;
                                                                                if (jj_scan_token(64)) {
                                                                                    jj_scanpos = xsp;
                                                                                    if (jj_scan_token(65))
                                                                                        return true;
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        if (jj_3R_30())
            return true;
        return false;
    }
    private boolean jj_3R_70() {
        if (jj_3R_74())
            return true;
        return false;
    }
    private boolean jj_3R_68() {
        if (jj_scan_token(COLON))
            return true;
        if (jj_3R_30())
            return true;
        return false;
    }
    private boolean jj_3R_69() {
        if (jj_3R_73())
            return true;
        return false;
    }
    private boolean jj_3R_66() {
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3R_69()) {
            jj_scanpos = xsp;
            if (jj_3R_70())
                return true;
        }
        return false;
    }
    private boolean jj_3R_12() {
        if (jj_3R_18())
            return true;
        Token xsp;
        xsp = jj_scanpos;
        if (jj_scan_token(44)) {
            jj_scanpos = xsp;
            if (jj_scan_token(45))
                return true;
        }
        return false;
    }
    private boolean jj_3_3() {
        if (jj_3R_8())
            return true;
        return false;
    }
    private boolean jj_3R_56() {
        if (jj_3R_66())
            return true;
        return false;
    }
    private boolean jj_3R_8() {
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3R_11()) {
            jj_scanpos = xsp;
            if (jj_3R_12())
                return true;
        }
        return false;
    }
    private boolean jj_3R_11() {
        Token xsp;
        xsp = jj_scanpos;
        if (jj_scan_token(43)) {
            jj_scanpos = xsp;
            if (jj_scan_token(44)) {
                jj_scanpos = xsp;
                if (jj_scan_token(45))
                    return true;
            }
        }
        if (jj_3R_18())
            return true;
        return false;
    }
    private boolean jj_3R_44() {
        if (jj_3R_18())
            return true;
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3R_56())
            jj_scanpos = xsp;
        return false;
    }
    private boolean jj_3R_55() {
        if (jj_3R_66())
            return true;
        return false;
    }
    private boolean jj_3R_63() {
        if (jj_scan_token(COLON))
            return true;
        if (jj_3R_30())
            return true;
        return false;
    }
    private boolean jj_3R_43() {
        if (jj_3R_8())
            return true;
        return false;
    }
    private boolean jj_3R_45() {
        if (jj_3R_9())
            return true;
        Token xsp;
        xsp = jj_scanpos;
        if (jj_scan_token(32))
            jj_scanpos = xsp;
        return false;
    }
    private boolean jj_3R_64() {
        if (jj_scan_token(COMMA))
            return true;
        if (jj_3R_57())
            return true;
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3R_68())
            jj_scanpos = xsp;
        return false;
    }
    private boolean jj_3R_30() {
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3R_42()) {
            jj_scanpos = xsp;
            if (jj_3R_43()) {
                jj_scanpos = xsp;
                if (jj_3R_44())
                    return true;
            }
        }
        return false;
    }
    private boolean jj_3R_42() {
        if (jj_scan_token(OPAR))
            return true;
        if (jj_3R_30())
            return true;
        if (jj_scan_token(CPAR))
            return true;
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3R_55())
            jj_scanpos = xsp;
        return false;
    }
    private boolean jj_3R_31() {
        Token xsp;
        while (true) {
            xsp = jj_scanpos;
            if (jj_3R_45()) {
                jj_scanpos = xsp;
                break;
            }
        }
        return false;
    }
    private boolean jj_3R_16() {
        if (jj_3R_22())
            return true;
        return false;
    }
    private boolean jj_3R_15() {
        if (jj_3R_21())
            return true;
        return false;
    }
    private boolean jj_3R_14() {
        if (jj_3R_20())
            return true;
        return false;
    }
    private boolean jj_3R_13() {
        if (jj_3R_19())
            return true;
        return false;
    }
    private boolean jj_3R_51() {
        if (jj_scan_token(OCBR))
            return true;
        if (jj_3R_57())
            return true;
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3R_63())
            jj_scanpos = xsp;
        while (true) {
            xsp = jj_scanpos;
            if (jj_3R_64()) {
                jj_scanpos = xsp;
                break;
            }
        }
        if (jj_scan_token(CCBR))
            return true;
        return false;
    }
    private boolean jj_3_7() {
        if (jj_3R_10())
            return true;
        return false;
    }
    private boolean jj_3R_9() {
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3R_13()) {
            jj_scanpos = xsp;
            if (jj_3R_14()) {
                jj_scanpos = xsp;
                if (jj_3R_15()) {
                    jj_scanpos = xsp;
                    if (jj_3R_16())
                        return true;
                }
            }
        }
        return false;
    }
    private boolean jj_3R_62() {
        if (jj_scan_token(COMMA))
            return true;
        if (jj_3R_30())
            return true;
        return false;
    }
    private boolean jj_3R_35() {
        if (jj_3R_30())
            return true;
        return false;
    }
    private boolean jj_3R_10() {
        if (jj_3R_17())
            return true;
        if (jj_scan_token(COMMA))
            return true;
        return false;
    }
    private boolean jj_3_2() {
        if (jj_scan_token(OCBR))
            return true;
        if (jj_scan_token(CCBR))
            return true;
        return false;
    }
    private boolean jj_3R_39() {
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3_2()) {
            jj_scanpos = xsp;
            if (jj_3R_51())
                return true;
        }
        return false;
    }
    private boolean jj_3R_34() {
        if (jj_3R_10())
            return true;
        if (jj_3R_30())
            return true;
        return false;
    }
    private boolean jj_3R_50() {
        if (jj_scan_token(OBRA))
            return true;
        if (jj_3R_30())
            return true;
        Token xsp;
        while (true) {
            xsp = jj_scanpos;
            if (jj_3R_62()) {
                jj_scanpos = xsp;
                break;
            }
        }
        if (jj_scan_token(CBRA))
            return true;
        return false;
    }
    private boolean jj_3R_22() {
        if (jj_scan_token(THROW))
            return true;
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3R_34()) {
            jj_scanpos = xsp;
            if (jj_3R_35())
                return true;
        }
        return false;
    }
    private boolean jj_3R_33() {
        if (jj_scan_token(ELSE))
            return true;
        if (jj_3R_31())
            return true;
        return false;
    }
    private boolean jj_3_1() {
        if (jj_scan_token(OBRA))
            return true;
        if (jj_scan_token(CBRA))
            return true;
        return false;
    }
    private boolean jj_3R_38() {
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3_1()) {
            jj_scanpos = xsp;
            if (jj_3R_50())
                return true;
        }
        return false;
    }
    private boolean jj_3R_32() {
        if (jj_scan_token(ELSEIF))
            return true;
        if (jj_scan_token(OPAR))
            return true;
        if (jj_3R_30())
            return true;
        if (jj_scan_token(CPAR))
            return true;
        if (jj_3R_31())
            return true;
        return false;
    }
    private boolean jj_3R_20() {
        if (jj_scan_token(IF))
            return true;
        if (jj_scan_token(OPAR))
            return true;
        if (jj_3R_30())
            return true;
        if (jj_scan_token(CPAR))
            return true;
        if (jj_3R_31())
            return true;
        Token xsp;
        while (true) {
            xsp = jj_scanpos;
            if (jj_3R_32()) {
                jj_scanpos = xsp;
                break;
            }
        }
        xsp = jj_scanpos;
        if (jj_3R_33())
            jj_scanpos = xsp;
        if (jj_scan_token(END))
            return true;
        return false;
    }
    private boolean jj_3R_17() {
        Token xsp;
        xsp = jj_scanpos;
        if (jj_scan_token(16)) {
            jj_scanpos = xsp;
            if (jj_scan_token(12)) {
                jj_scanpos = xsp;
                if (jj_scan_token(13)) {
                    jj_scanpos = xsp;
                    if (jj_scan_token(14)) {
                        jj_scanpos = xsp;
                        if (jj_scan_token(15))
                            return true;
                    }
                }
            }
        }
        return false;
    }
    private boolean jj_3R_58() {
        Token xsp;
        xsp = jj_scanpos;
        if (jj_scan_token(25)) {
            jj_scanpos = xsp;
            if (jj_scan_token(26))
                return true;
        }
        return false;
    }
    private boolean jj_3R_21() {
        if (jj_scan_token(RETURN))
            return true;
        if (jj_3R_30())
            return true;
        return false;
    }
    private boolean jj_3_6() {
        if (jj_3R_9())
            return true;
        return false;
    }
    private boolean jj_3R_29() {
        if (jj_3R_30())
            return true;
        return false;
    }
    private boolean jj_3R_28() {
        if (jj_3R_41())
            return true;
        return false;
    }
    private boolean jj_3R_57() {
        Token xsp;
        xsp = jj_scanpos;
        if (jj_scan_token(69)) {
            jj_scanpos = xsp;
            if (jj_scan_token(71)) {
                jj_scanpos = xsp;
                if (jj_scan_token(72))
                    return true;
            }
        }
        return false;
    }
    private boolean jj_3R_19() {
        if (jj_scan_token(VAR))
            return true;
        if (jj_3R_27())
            return true;
        if (jj_scan_token(ASS))
            return true;
        Token xsp;
        xsp = jj_scanpos;
        if (jj_3R_28()) {
            jj_scanpos = xsp;
            if (jj_3R_29())
                return true;
        }
        return false;
    }
    private boolean jj_3R_54() {
        if (jj_3R_9())
            return true;
        return false;
    }
    private boolean jj_3R_65() {
        if (jj_scan_token(COMMA))
            return true;
        if (jj_scan_token(IDENTIFIER))
            return true;
        return false;
    }
    private boolean jj_3R_40() {
        if (jj_scan_token(OCBRR))
            return true;
        if (jj_scan_token(IDENTIFIER))
            return true;
        if (jj_scan_token(CCBR))
            return true;
        return false;
    }
    private boolean jj_3R_53() {
        if (jj_scan_token(OCBR))
            return true;
        if (jj_3R_31())
            return true;
        if (jj_scan_token(CCBR))
            return true;
        return false;
    }
    private boolean jj_3R_27() {
        Token xsp;
        xsp = jj_scanpos;
        if (jj_scan_token(75)) {
            jj_scanpos = xsp;
            if (jj_3R_40())
                return true;
        }
        return false;
    }
    /** Generated Token Manager. */
    public GraphParserTokenManager token_source;
    JavaCharStream jj_input_stream;
    /** Current token. */
    public  Token token;
    /** Next token. */
    public  Token jj_nt;
    private int   jj_ntk;
    private Token jj_scanpos, jj_lastpos;
    private int jj_la;
    private int jj_gen;
    final private int[] jj_la1 = new int[38];
    static private int[] jj_la1_0;
    static private int[] jj_la1_1;
    static private int[] jj_la1_2;

    static {
        jj_la1_init_0();
        jj_la1_init_1();
        jj_la1_init_2();
    }

    private static void jj_la1_init_0() {
        jj_la1_0 = new int[] { 0x0, 0x0, 0x6000000, 0x1f000, 0x20000000, 0x0, 0x40000000, 0x20000000, 0x40000000, 0x0, 0x80000000, 0x80000000, 0x0, 0xe01f000, 0x0, 0x0, 0xe01f000, 0x80000000, 0x0, 0x0, 0xe01f000, 0xe01f000, 0x20000000, 0x0, 0xf01f000, 0x0, 0x20000000, 0x0, 0x0, 0xf01f000, 0x40000, 0x80000, 0xe01f000, 0xe20000, 0xe20000, 0x0, 0x10000000, 0x0, };
    }
    private static void jj_la1_init_1() {
        jj_la1_1 = new int[] { 0x100, 0x0, 0x0, 0x0, 0x0, 0x40, 0x0, 0x0, 0x0, 0x200, 0xffffc000, 0xffffc000, 0x10, 0x340, 0x3800, 0x3000, 0x3b40, 0xffffc000, 0xffffc000, 0x10, 0x340, 0x0, 0x0, 0x10, 0x3b50, 0x240, 0x0, 0x10, 0x200, 0x3b50, 0x0, 0x0, 0x3b50, 0x0, 0x0, 0x1, 0x0, 0x1, };
    }
    private static void jj_la1_init_2() {
        jj_la1_2 = new int[] { 0x800, 0x1a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3, 0x3, 0x0, 0x9a0, 0x0, 0x0, 0x9a0, 0x3, 0x3, 0x0, 0x9a0, 0x1a0, 0x0, 0x0, 0x9a0, 0x1000, 0x0, 0x0, 0x0, 0x9a0, 0x0, 0x0, 0x9a0, 0x0, 0x0, 0x0, 0x0, 0x0, };
    }
    final private JJCalls[] jj_2_rtns = new JJCalls[7];
    private       boolean   jj_rescan = false;
    private       int       jj_gc     = 0;
    /** Constructor with InputStream. */
    public GraphParser(java.io.InputStream stream) {
        this(stream, null);
    }
    /** Constructor with InputStream and supplied encoding */
    public GraphParser(java.io.InputStream stream, String encoding) {
        try {
            jj_input_stream = new JavaCharStream(stream, encoding, 1, 1);
        } catch (java.io.UnsupportedEncodingException e) {
            throw new RuntimeException(e);
        }
        token_source = new GraphParserTokenManager(jj_input_stream);
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 38; i++)
            jj_la1[i] = -1;
        for (int i = 0; i < jj_2_rtns.length; i++)
            jj_2_rtns[i] = new JJCalls();
    }
    /** Reinitialise. */
    public void ReInit(java.io.InputStream stream) {
        ReInit(stream, null);
    }
    /** Reinitialise. */
    public void ReInit(java.io.InputStream stream, String encoding) {
        try {
            jj_input_stream.ReInit(stream, encoding, 1, 1);
        } catch (java.io.UnsupportedEncodingException e) {
            throw new RuntimeException(e);
        }
        token_source.ReInit(jj_input_stream);
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 38; i++)
            jj_la1[i] = -1;
        for (int i = 0; i < jj_2_rtns.length; i++)
            jj_2_rtns[i] = new JJCalls();
    }
    /** Constructor. */
    public GraphParser(java.io.Reader stream) {
        jj_input_stream = new JavaCharStream(stream, 1, 1);
        token_source = new GraphParserTokenManager(jj_input_stream);
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 38; i++)
            jj_la1[i] = -1;
        for (int i = 0; i < jj_2_rtns.length; i++)
            jj_2_rtns[i] = new JJCalls();
    }
    /** Reinitialise. */
    public void ReInit(java.io.Reader stream) {
        jj_input_stream.ReInit(stream, 1, 1);
        token_source.ReInit(jj_input_stream);
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 38; i++)
            jj_la1[i] = -1;
        for (int i = 0; i < jj_2_rtns.length; i++)
            jj_2_rtns[i] = new JJCalls();
    }
    /** Constructor with generated Token Manager. */
    public GraphParser(GraphParserTokenManager tm) {
        token_source = tm;
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 38; i++)
            jj_la1[i] = -1;
        for (int i = 0; i < jj_2_rtns.length; i++)
            jj_2_rtns[i] = new JJCalls();
    }
    /** Reinitialise. */
    public void ReInit(GraphParserTokenManager tm) {
        token_source = tm;
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 38; i++)
            jj_la1[i] = -1;
        for (int i = 0; i < jj_2_rtns.length; i++)
            jj_2_rtns[i] = new JJCalls();
    }
    private Token jj_consume_token(int kind) throws ParseException {
        Token oldToken;
        if ((oldToken = token).next != null)
            token = token.next;
        else
            token = token.next = token_source.getNextToken();
        jj_ntk = -1;
        if (token.kind == kind) {
            jj_gen++;
            if (++jj_gc > 100) {
                jj_gc = 0;
                for (int i = 0; i < jj_2_rtns.length; i++) {
                    JJCalls c = jj_2_rtns[i];
                    while (c != null) {
                        if (c.gen < jj_gen)
                            c.first = null;
                        c = c.next;
                    }
                }
            }
            return token;
        }
        token = oldToken;
        jj_kind = kind;
        throw generateParseException();
    }
    @SuppressWarnings("serial")
    static private final class LookaheadSuccess extends java.lang.Error {
    }
    final private LookaheadSuccess jj_ls = new LookaheadSuccess();
    private boolean jj_scan_token(int kind) {
        if (jj_scanpos == jj_lastpos) {
            jj_la--;
            if (jj_scanpos.next == null) {
                jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
            } else {
                jj_lastpos = jj_scanpos = jj_scanpos.next;
            }
        } else {
            jj_scanpos = jj_scanpos.next;
        }
        if (jj_rescan) {
            int i = 0;
            Token tok = token;
            while (tok != null && tok != jj_scanpos) {
                i++;
                tok = tok.next;
            }
            if (tok != null)
                jj_add_error_token(kind, i);
        }
        if (jj_scanpos.kind != kind)
            return true;
        if (jj_la == 0 && jj_scanpos == jj_lastpos)
            throw jj_ls;
        return false;
    }
    /** Get the next Token. */
    final public Token getNextToken() {
        if (token.next != null)
            token = token.next;
        else
            token = token.next = token_source.getNextToken();
        jj_ntk = -1;
        jj_gen++;
        return token;
    }
    /** Get the specific Token. */
    final public Token getToken(int index) {
        Token t = token;
        for (int i = 0; i < index; i++) {
            if (t.next != null)
                t = t.next;
            else
                t = t.next = token_source.getNextToken();
        }
        return t;
    }
    private int jj_ntk_f() {
        if ((jj_nt = token.next) == null)
            return (jj_ntk = (token.next = token_source.getNextToken()).kind);
        else
            return (jj_ntk = jj_nt.kind);
    }
    private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
    private int[] jj_expentry;
    private int   jj_kind       = -1;
    private int[] jj_lasttokens = new int[100];
    private int jj_endpos;
    private void jj_add_error_token(int kind, int pos) {
        if (pos >= 100)
            return;
        if (pos == jj_endpos + 1) {
            jj_lasttokens[jj_endpos++] = kind;
        } else if (jj_endpos != 0) {
            jj_expentry = new int[jj_endpos];
            for (int i = 0; i < jj_endpos; i++) {
                jj_expentry[i] = jj_lasttokens[i];
            }
            jj_entries_loop:
            for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext(); ) {
                int[] oldentry = (int[]) (it.next());
                if (oldentry.length == jj_expentry.length) {
                    for (int i = 0; i < jj_expentry.length; i++) {
                        if (oldentry[i] != jj_expentry[i]) {
                            continue jj_entries_loop;
                        }
                    }
                    jj_expentries.add(jj_expentry);
                    break jj_entries_loop;
                }
            }
            if (pos != 0)
                jj_lasttokens[(jj_endpos = pos) - 1] = kind;
        }
    }
    /** Generate ParseException. */
    public ParseException generateParseException() {
        jj_expentries.clear();
        boolean[] la1tokens = new boolean[78];
        if (jj_kind >= 0) {
            la1tokens[jj_kind] = true;
            jj_kind = -1;
        }
        for (int i = 0; i < 38; i++) {
            if (jj_la1[i] == jj_gen) {
                for (int j = 0; j < 32; j++) {
                    if ((jj_la1_0[i] & (1 << j)) != 0) {
                        la1tokens[j] = true;
                    }
                    if ((jj_la1_1[i] & (1 << j)) != 0) {
                        la1tokens[32 + j] = true;
                    }
                    if ((jj_la1_2[i] & (1 << j)) != 0) {
                        la1tokens[64 + j] = true;
                    }
                }
            }
        }
        for (int i = 0; i < 78; i++) {
            if (la1tokens[i]) {
                jj_expentry = new int[1];
                jj_expentry[0] = i;
                jj_expentries.add(jj_expentry);
            }
        }
        jj_endpos = 0;
        jj_rescan_token();
        jj_add_error_token(0, 0);
        int[][] exptokseq = new int[jj_expentries.size()][];
        for (int i = 0; i < jj_expentries.size(); i++) {
            exptokseq[i] = jj_expentries.get(i);
        }
        return new ParseException(token, exptokseq, tokenImage);
    }
    /** Enable tracing. */
    final public void enable_tracing() {
    }
    /** Disable tracing. */
    final public void disable_tracing() {
    }
    private void jj_rescan_token() {
        jj_rescan = true;
        for (int i = 0; i < 7; i++) {
            try {
                JJCalls p = jj_2_rtns[i];
                do {
                    if (p.gen > jj_gen) {
                        jj_la = p.arg;
                        jj_lastpos = jj_scanpos = p.first;
                        switch (i) {
                        case 0:
                            jj_3_1();
                            break;
                        case 1:
                            jj_3_2();
                            break;
                        case 2:
                            jj_3_3();
                            break;
                        case 3:
                            jj_3_4();
                            break;
                        case 4:
                            jj_3_5();
                            break;
                        case 5:
                            jj_3_6();
                            break;
                        case 6:
                            jj_3_7();
                            break;
                        }
                    }
                    p = p.next;
                } while (p != null);
            } catch (LookaheadSuccess ls) {
            }
        }
        jj_rescan = false;
    }
    private void jj_save(int index, int xla) {
        JJCalls p = jj_2_rtns[index];
        while (p.gen > jj_gen) {
            if (p.next == null) {
                p = p.next = new JJCalls();
                break;
            }
            p = p.next;
        }
        p.gen = jj_gen + xla - jj_la;
        p.first = token;
        p.arg = xla;
    }
    static final class JJCalls {
        int     gen;
        Token   first;
        int     arg;
        JJCalls next;
    }
}
