create table RSF_SERVICE (
	si_id			BIGINT			NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	
	si_bindID		VARCHAR(350)	NOT NULL,
	si_bindGroup	VARCHAR(100)	NOT NULL,
	si_bindName		VARCHAR(200)	NOT NULL,
	si_bindVersion	VARCHAR(50)		NOT NULL,
	si_bindType		VARCHAR(300)	NOT NULL,
	
	si_status		INTEGER			NOT NULL,
	si_beat_time	DATETIME		NOT NULL,
	
	si_forAppCoe	VARCHAR(100)		NULL,
	si_feature		VARCHAR(500)	NOT NULL,
	PRIMARY KEY (si_id)
);
create index RSF_SERVICE_INDEX on RSF_SERVICE si_bindID asc;
create index RSF_SERVICE_INDEX on RSF_SERVICE si_bindGroup,si_bindName,si_bindVersion asc;