create table RSF_SERVER (
	ser_id			BIGINT			NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	
	ser_rsfURL		VARCHAR(200)	NOT NULL,
	ser_bindAddress	VARCHAR(100)	NOT NULL,
	ser_bindPort	VARCHAR(6)		NOT NULL,
	ser_unit		VARCHAR(50)		NOT NULL,
	ser_version		VARCHAR(50)		NOT NULL,
	
	ser_beat		DATETIME		NOT NULL,
	ser_salt		VARCHAR(50)			NULL,
	ser_status		INTEGER			NOT NULL,
	
	ser_create_time	DATETIME		NOT NULL,
	ser_modify_time	DATETIME		NOT NULL,
	PRIMARY KEY (ser_id)
);
create index RSF_SERVER_INDEX on RSF_SERVER ser_salt asc;