create table RSF_TERMINAL (
	ter_id				BIGINT			NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	
	ter_rsfURL			VARCHAR(200)	NOT NULL,
	ter_hostPort		VARCHAR(100)	NOT NULL,
	ter_unit			VARCHAR(50)		NOT NULL,

	ter_forBindID		VARCHAR(50)		NOT NULL,
	ter_persona			CHAR(1)			NOT NULL,
	ter_status			INTEGER			NOT NULL,
	ter_salt			VARCHAR(50)			NULL,
	ter_beat_time		DATETIME		NOT NULL,

	ter_timeout			INTEGER			NOT NULL,
	ter_serializeType	VARCHAR(50)		NOT NULL,
	ter_feature			VARCHAR(500)	NOT NULL,
	PRIMARY KEY (ter_id)
);